name: SABnzbd.org

# Needs to be a string, for string-comparison
wiki_version: '2.2'

giganews_link: 'https://www.giganews.com/usenet-special/'
supernews_link: 'https://www.supernews.com/special/usenet-special/'

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      name: SABnzbd.org
  -
    scope:
      path: "wiki"
    values:
      layout: "wiki"
      section: "Wiki"
